#!/usr/bin/env python3
"""Generate Clash/mihomo rule-provider files from Surge rulesets.

The repository keeps Surge rule sets as the canonical generated output under
``Rule/*.list``. This script mirrors those files into Clash-compatible
``classical`` rule-provider YAML files under ``clash/*.yaml``.

The payload intentionally keeps the rule body policy-free, matching Clash rule
provider syntax:

    payload:
      - 'DOMAIN-SUFFIX,example.com'

Only Python stdlib is used so the script can run in GitHub Actions without
additional dependencies.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

RULE_DIR = Path("Rule")
CLASH_DIR = Path("clash")

# Surge-only rule types that mihomo/Clash cannot evaluate at all. USER-AGENT
# matches the HTTP User-Agent header and URL-REGEX matches full request URLs;
# neither concept exists in Clash/mihomo, so such rules would be silently
# ignored and only bloat the payload. We drop them from the generated Clash
# providers while keeping them in the canonical Surge Rule/*.list.
CLASH_UNSUPPORTED_TYPES = {
    "URL-REGEX",
    "USER-AGENT",
}

# Clash/mihomo classical rule-provider payload types generated by this mirror.
# Keep this allow-list conservative: unsupported Surge-only types must be
# filtered before rendering and rejected again during validation.
CLASH_CLASSICAL_ALLOWED_TYPES = {
    "DOMAIN",
    "DOMAIN-SUFFIX",
    "DOMAIN-KEYWORD",
    "DOMAIN-WILDCARD",
    "IP-CIDR",
    "IP-CIDR6",
    "IP-ASN",
    "GEOIP",
    "PROCESS-NAME",
}

# Clash Premium supports the core types. mihomo supports a broader superset such
# as DOMAIN-WILDCARD and IP-ASN. We preserve them rather than silently dropping
# rules, and emit a summary so compatibility-sensitive users can audit them.
MIHOMO_ONLY_OR_COMPAT_TYPES = {
    "DOMAIN-WILDCARD",
    "IP-ASN",
    "PROCESS-NAME",
}

# Large domain-heavy sources additionally get a mihomo `behavior: domain` export
# (<stem>_Domain.yaml, trie-matched) plus a small classical remainder
# (<stem>_Extra.yaml) holding the non DOMAIN/DOMAIN-SUFFIX rules, so clients can
# avoid linearly scanning huge classical payloads. The classical <stem>.yaml is
# still generated unchanged for compatibility.
DOMAIN_SPLIT_SOURCES = {"China"}

HEADER_RE = re.compile(r"^#\s*(TOTAL|UPDATED|SOURCES|Generated|Source)", re.IGNORECASE)


def yaml_quote(value: str) -> str:
    """Return a YAML single-quoted scalar."""
    return "'" + value.replace("'", "''") + "'"


def parse_surge_file(path: Path) -> tuple[list[str], list[str]]:
    """Split a Surge .list file into header comments and payload rules."""
    comments: list[str] = []
    rules: list[str] = []

    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line:
            continue
        if line.startswith("#"):
            if HEADER_RE.match(line):
                comments.append(line)
            continue
        rule_type = line.split(",", 1)[0].strip()
        if rule_type in CLASH_UNSUPPORTED_TYPES:
            continue
        rules.append(line)

    return comments, rules


def clash_path_for(source: Path) -> Path:
    return CLASH_DIR / f"{source.stem}.yaml"


def domain_split_paths_for(source: Path) -> tuple[Path, Path]:
    return (
        CLASH_DIR / f"{source.stem}_Domain.yaml",
        CLASH_DIR / f"{source.stem}_Extra.yaml",
    )


def split_domain_rules(rules: list[str]) -> tuple[list[str], list[str]]:
    """Split rules into domain-behavior payload entries and the remainder."""
    domains: list[str] = []
    extras: list[str] = []
    for rule in rules:
        parts = [part.strip() for part in rule.split(",")]
        if len(parts) >= 2 and parts[0] == "DOMAIN-SUFFIX":
            domains.append(f"+.{parts[1]}")
        elif len(parts) >= 2 and parts[0] == "DOMAIN":
            domains.append(parts[1])
        else:
            extras.append(rule)
    return domains, extras


def non_total_comments(comments: list[str]) -> list[str]:
    return [c for c in comments if not c.upper().lstrip("# ").startswith("TOTAL")]


def render_clash_yaml(source: Path, comments: list[str], rules: list[str]) -> str:
    lines = [
        f"# Generated from {source.as_posix()}",
        "# Format: Clash/mihomo rule-provider, behavior: classical",
    ]
    lines.extend(comments)
    lines.append("payload:")
    lines.extend(f"  - {yaml_quote(rule)}" for rule in rules)
    lines.append("")
    return "\n".join(lines)


def render_domain_yaml(source: Path, comments: list[str], domains: list[str]) -> str:
    lines = [
        f"# Generated from {source.as_posix()} (DOMAIN/DOMAIN-SUFFIX entries only)",
        "# Format: Clash/mihomo rule-provider, behavior: domain",
    ]
    lines.extend(non_total_comments(comments))
    lines.append(f"# TOTAL: {len(domains)}")
    lines.append("payload:")
    lines.extend(f"  - {yaml_quote(domain)}" for domain in domains)
    lines.append("")
    return "\n".join(lines)


def render_extra_yaml(source: Path, comments: list[str], extras: list[str]) -> str:
    lines = [
        f"# Generated from {source.as_posix()} (rules not covered by the _Domain export)",
        "# Format: Clash/mihomo rule-provider, behavior: classical",
    ]
    lines.extend(non_total_comments(comments))
    lines.append(f"# TOTAL: {len(extras)}")
    lines.append("payload:")
    lines.extend(f"  - {yaml_quote(rule)}" for rule in extras)
    lines.append("")
    return "\n".join(lines)


def generate(check: bool = False) -> int:
    if not RULE_DIR.is_dir():
        raise SystemExit(f"Rule directory not found: {RULE_DIR}")

    sources = sorted(RULE_DIR.glob("*.list"))
    if not sources:
        raise SystemExit("No Rule/*.list files found")

    CLASH_DIR.mkdir(parents=True, exist_ok=True)
    errors: list[str] = []
    total_rules = 0
    compat_counts: dict[str, int] = {}

    expected_files = {clash_path_for(source) for source in sources}
    for source in sources:
        if source.stem in DOMAIN_SPLIT_SOURCES:
            expected_files.update(domain_split_paths_for(source))

    def emit(out_path: Path, rendered: str) -> None:
        if check:
            existing = out_path.read_text(encoding="utf-8") if out_path.exists() else None
            if existing != rendered:
                errors.append(f"out of date: {out_path}")
        else:
            out_path.write_text(rendered, encoding="utf-8", newline="\n")

    for source in sources:
        comments, rules = parse_surge_file(source)
        total_rules += len(rules)
        for rule in rules:
            rule_type = rule.split(",", 1)[0]
            if rule_type in MIHOMO_ONLY_OR_COMPAT_TYPES:
                compat_counts[rule_type] = compat_counts.get(rule_type, 0) + 1

        emit(clash_path_for(source), render_clash_yaml(source, comments, rules))

        if source.stem in DOMAIN_SPLIT_SOURCES:
            domains, extras = split_domain_rules(rules)
            domain_path, extra_path = domain_split_paths_for(source)
            emit(domain_path, render_domain_yaml(source, comments, domains))
            emit(extra_path, render_extra_yaml(source, comments, extras))

    # Remove stale Clash files when the Surge source was deleted/renamed.
    for stale in sorted(CLASH_DIR.glob("*.yaml")):
        if stale not in expected_files:
            if check:
                errors.append(f"stale file: {stale}")
            else:
                stale.unlink()

    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1

    print(f"Generated {len(sources)} Clash rule-provider files with {total_rules} payload rules.")
    if compat_counts:
        detail = ", ".join(f"{k}:{v}" for k, v in sorted(compat_counts.items()))
        print(f"Compatibility note: preserved mihomo/extended rule types: {detail}")
    return 0


def parse_payload_scalar(raw: str) -> str:
    """Parse the YAML single-quoted payload scalar emitted by this script."""
    value = raw[4:].strip()
    if not (value.startswith("'") and value.endswith("'")):
        raise ValueError("payload item is not a single-quoted scalar")
    return value[1:-1].replace("''", "'")


def validate_payload_file(out_path: Path, behavior: str, errors: list[str]) -> int:
    """Validate generated YAML shape, payload quoting, and Clash rule types."""
    payload_rules = 0
    seen_payload = False
    for lineno, raw in enumerate(out_path.read_text(encoding="utf-8").splitlines(), 1):
        if raw == "payload:":
            seen_payload = True
            continue
        if not raw.startswith("  - "):
            continue

        payload_rules += 1
        try:
            value = parse_payload_scalar(raw)
        except ValueError as exc:
            errors.append(f"invalid payload scalar in {out_path}:{lineno}: {exc}")
            continue

        if behavior == "domain":
            if not value or "," in value:
                errors.append(f"invalid domain-behavior payload in {out_path}:{lineno}: {value}")
            continue

        rule_type = value.split(",", 1)[0].strip()
        if rule_type in CLASH_UNSUPPORTED_TYPES:
            errors.append(f"unsupported Clash rule type in {out_path}:{lineno}: {value}")
        elif rule_type not in CLASH_CLASSICAL_ALLOWED_TYPES:
            errors.append(f"unknown Clash rule type in {out_path}:{lineno}: {value}")
    if not seen_payload:
        errors.append(f"missing payload key: {out_path}")
    return payload_rules


def validate_payload_counts() -> int:
    """Validate generated YAML shape, type compatibility, and payload counts."""
    errors: list[str] = []
    for source in sorted(RULE_DIR.glob("*.list")):
        out_path = clash_path_for(source)
        if not out_path.exists():
            errors.append(f"missing output: {out_path}")
            continue
        _, source_rules = parse_surge_file(source)
        payload_count = validate_payload_file(out_path, "classical", errors)
        if payload_count != len(source_rules):
            errors.append(
                f"payload count mismatch for {out_path}: "
                f"{payload_count} != {len(source_rules)}"
            )
        if source.stem in DOMAIN_SPLIT_SOURCES:
            domain_path, extra_path = domain_split_paths_for(source)
            if not domain_path.exists() or not extra_path.exists():
                errors.append(f"missing domain split outputs for: {source}")
                continue
            split_total = validate_payload_file(domain_path, "domain", errors) + validate_payload_file(
                extra_path, "classical", errors
            )
            if split_total != len(source_rules):
                errors.append(
                    f"domain split count mismatch for {source}: "
                    f"{split_total} != {len(source_rules)}"
                )
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        return 1
    print("Clash payload validation passed.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    parser.add_argument("--validate", action="store_true", help="validate generated payload counts")
    args = parser.parse_args()

    status = generate(check=args.check)
    if status != 0:
        return status
    if args.validate:
        return validate_payload_counts()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
