#!/usr/bin/env python3
"""Repository invariant checks for linnux-x/surge.

This script intentionally uses only the Python standard library so it can run
both locally and inside GitHub Actions without dependency setup.
"""
from __future__ import annotations

import re
import sys
from collections import defaultdict
from pathlib import Path

# Ensure scripts/ is on the path
_scripts_dir = str(Path(__file__).resolve().parent)
if _scripts_dir not in sys.path:
    sys.path.insert(0, _scripts_dir)

from rule_validator import (
    validate_rule_file, parse_total_header, non_comment_rules,
    ALLOWED_TYPES, OPTION_TOKENS, SUKKAW_MARKER,
)

ROOT = Path(__file__).resolve().parents[1]
RULE_DIR = ROOT / "Rule"
WORKFLOW_DIR = ROOT / ".github" / "workflows"
MAIN_WORKFLOW = WORKFLOW_DIR / "auto-rules.yml"
README = ROOT / "README.md"

# Import shared validator — constants and functions come from rule_validator now


def rel(path: Path) -> str:
    return str(path.relative_to(ROOT))


def extract_process_rule_targets() -> set[str]:
    """Return all expected ruleset filenames from the single source of truth."""
    from sources import ALL_RULESETS
    return ALL_RULESETS.copy()


def extract_workflow_name(text: str) -> str | None:
    match = re.search(r"^name:\s*(.+?)\s*$", text, flags=re.M)
    return match.group(1).strip().strip('"\'') if match else None


def has_schedule_trigger(text: str) -> bool:
    lines = text.splitlines()
    in_on = False
    on_indent = None
    for line in lines:
        if re.match(r"^on:\s*$", line):
            in_on = True
            on_indent = 0
            continue
        if in_on:
            if line and not line.startswith((" ", "\t")) and not line.lstrip().startswith("#"):
                in_on = False
                continue
            if re.match(r"^\s+schedule:\s*$", line):
                return True
    return False


def check_workflow_inventory(errors: list[str]) -> None:
    if not MAIN_WORKFLOW.exists():
        errors.append(f"Missing main workflow: {rel(MAIN_WORKFLOW)}")
        return
    rule_files = {p.name for p in RULE_DIR.glob("*.list")}
    targets = extract_process_rule_targets()
    missing_in_workflow = sorted(rule_files - targets)
    missing_files = sorted(targets - rule_files)
    if missing_in_workflow:
        errors.append("Rule files not generated by main workflow: " + ", ".join(missing_in_workflow))
    if missing_files:
        errors.append("Main workflow targets missing Rule/*.list files: " + ", ".join(missing_files))


def check_workflow_names_and_deprecated_schedule(errors: list[str], warnings: list[str]) -> None:
    names: dict[str, list[Path]] = defaultdict(list)
    for path in sorted(WORKFLOW_DIR.glob("*.yml")):
        text = path.read_text(encoding="utf-8", errors="replace")
        name = extract_workflow_name(text)
        if name:
            names[name].append(path)
        if path.name != MAIN_WORKFLOW.name and has_schedule_trigger(text):
            stale_rule_workflow = (
                path.name == "auto-surge-rules.yml"
                or "process_rule" in text
                or re.search(r"\bRule/[A-Za-z0-9_]+[.]list\b", text)
            )
            if stale_rule_workflow:
                errors.append(f"Deprecated/non-main rule workflow still has schedule trigger: {rel(path)}")
    for name, paths in sorted(names.items()):
        if len(paths) > 1:
            errors.append("Duplicate GitHub Actions workflow name " + repr(name) + ": " + ", ".join(rel(p) for p in paths))
    if not names:
        warnings.append("No workflow names found")


def check_readme_inventory(errors: list[str]) -> None:
    if not README.exists():
        errors.append("README.md is missing")
        return
    text = README.read_text(encoding="utf-8", errors="replace")
    # Match backtick-wrapped filenames
    listed = set(re.findall(r"`([A-Za-z0-9_]+\.list)`", text))
    # Also match rule table rows: | emoji filename.list |
    listed |= set(re.findall(r"^\|\s*[^\s|]+\s+([A-Za-z0-9_]+\.list)\s+\|", text, re.M))
    rule_files = {p.name for p in RULE_DIR.glob("*.list")}
    stale = sorted(listed - rule_files)
    missing = sorted(rule_files - listed)
    if stale:
        errors.append("README mentions non-existent rule files: " + ", ".join(stale))
    if missing:
        errors.append("README omits rule files: " + ", ".join(missing))


def check_rule_files(errors: list[str]) -> None:
    for path in sorted(RULE_DIR.glob("*.list")):
        rules = [l for l in path.read_text(encoding="utf-8", errors="replace").splitlines()
                 if l.strip() and not l.strip().startswith("#")]
        total = parse_total_header(path)
        if total is not None and total != len(rules):
            errors.append(f"{rel(path)} TOTAL header {total} ≠ actual {len(rules)}")
        errs = validate_rule_file(rules, path.name)
        for e in errs:
            errors.append(f"{rel(path)} {e}")


def main() -> int:
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--ci", action="store_true",
                        help="CI mode: skip workflow-inventory and README-consistency checks")
    args = parser.parse_args()

    errors: list[str] = []
    warnings: list[str] = []

    if not args.ci:
        check_workflow_inventory(errors)
        check_readme_inventory(errors)
    check_workflow_names_and_deprecated_schedule(errors, warnings)
    check_rule_files(errors)

    if warnings:
        print("WARNINGS:")
        for warning in warnings:
            print(f"- {warning}")
    if errors:
        print("VALIDATION FAILED:")
        for error in errors:
            print(f"- {error}")
        return 1

    print("VALIDATION PASSED")
    print(f"Rule files: {len(list(RULE_DIR.glob('*.list')))}")
    print(f"Main workflow targets: {len(extract_process_rule_targets())}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
